#!/bin/bash

# set python version
PYTHON="python3.12"

# deps
DEPS="$PYTHON $PYTHON-venv $PYTHON-tk unzip curl"
# check what flavor of linux and install deps
FAIL() { echo "Unsupported Linux distribution $1"; exit 1; }
if [ -f /etc/os-release ]; then
    . /etc/os-release
    if [ "$ID" == "ubuntu" ]; then
        sudo apt-get update || exit 1
        sudo apt-get install -y $DEPS || exit 1
    elif [ "$ID" == "fedora" ]; then
        sudo dnf install -y $DEPS || exit 1
    elif [ "$ID" == "centos" ]; then
        sudo yum install -y $DEPS || exit 1
    elif [ "$ID" == "arch" ]; then
        sudo pacman -SU --noconfirm $DEPS || exit 1
    elif [ "$ID" == "manjaro" ]; then
        sudo pacman -SU --noconfirm $DEPS || exit 1
    else
        FAIL "$ID"
    fi
else
    FAIL "$ID"
fi

# create virtual environment
$PYTHON -m venv --symlinks --clear venv || exit 1
. ./venv/bin/activate || exit 1
python -m pip install -r requirements.txt || exit 1

# download databases
chmod +x download_imdb_data.sh || exit 1
./download_imdb_data.sh || exit 1
